import type { AppDefinition } from '../types';

export const APPS: AppDefinition[] = [
  {
    id: 'file-station',
    name: 'File Station',
    icon: '📁',
    description: 'Administrador de archivos del sistema',
    defaultWidth: 920,
    defaultHeight: 620,
    minWidth: 640,
    minHeight: 420,
    color: '#f59e0b',
  },
  {
    id: 'control-panel',
    name: 'Panel de Control',
    icon: '⚙️',
    description: 'Configuración completa del sistema',
    defaultWidth: 980,
    defaultHeight: 660,
    minWidth: 760,
    minHeight: 520,
    color: '#6366f1',
  },
  {
    id: 'package-center',
    name: 'Centro de Paquetes',
    icon: '📦',
    description: 'Instalar y gestionar aplicaciones',
    defaultWidth: 880,
    defaultHeight: 620,
    minWidth: 640,
    minHeight: 420,
    color: '#10b981',
  },
  {
    id: 'terminal',
    name: 'Terminal',
    icon: '💻',
    description: 'Consola del sistema',
    defaultWidth: 720,
    defaultHeight: 460,
    minWidth: 400,
    minHeight: 300,
    color: '#1e3a5f',
  },
  {
    id: 'text-editor',
    name: 'Editor de Texto',
    icon: '📝',
    description: 'Editor de archivos de texto',
    defaultWidth: 760,
    defaultHeight: 560,
    minWidth: 420,
    minHeight: 320,
    color: '#3b82f6',
  },
  {
    id: 'calculator',
    name: 'Calculadora',
    icon: '🧮',
    description: 'Calculadora científica',
    defaultWidth: 300,
    defaultHeight: 460,
    minWidth: 260,
    minHeight: 400,
    color: '#8b5cf6',
  },
  {
    id: 'system-info',
    name: 'Monitor del Sistema',
    icon: '📊',
    description: 'CPU, RAM, disco, red y procesos en tiempo real',
    defaultWidth: 820,
    defaultHeight: 580,
    minWidth: 600,
    minHeight: 420,
    color: '#ef4444',
  },
  {
    id: 'network-services',
    name: 'Servicios de Red',
    icon: '🌐',
    description: 'Configuración de red, DHCP, DNS y firewall',
    defaultWidth: 860,
    defaultHeight: 600,
    minWidth: 640,
    minHeight: 440,
    color: '#0891b2',
  },
  {
    id: 'ssh-manager',
    name: 'SSH Manager',
    icon: '🔐',
    description: 'Gestión de conexiones y claves SSH',
    defaultWidth: 780,
    defaultHeight: 560,
    minWidth: 580,
    minHeight: 400,
    color: '#334155',
  },
  {
    id: 'task-manager',
    name: 'Administrador de Tareas',
    icon: '📋',
    description: 'Gestión de procesos y tareas programadas',
    defaultWidth: 760,
    defaultHeight: 540,
    minWidth: 560,
    minHeight: 400,
    color: '#d946ef',
  },
  {
    id: 'log-center',
    name: 'Centro de Registros',
    icon: '📜',
    description: 'Visor de logs del sistema',
    defaultWidth: 880,
    defaultHeight: 580,
    minWidth: 640,
    minHeight: 420,
    color: '#64748b',
  },
  {
    id: 'vpn-manager',
    name: 'Gestor VPN',
    icon: '🔒',
    description: 'Configuración de conexiones VPN',
    defaultWidth: 720,
    defaultHeight: 520,
    minWidth: 540,
    minHeight: 380,
    color: '#059669',
  },
  {
    id: 'user-manager',
    name: 'Gestor de Usuarios',
    icon: '👥',
    description: 'Administración de usuarios y grupos',
    defaultWidth: 800,
    defaultHeight: 560,
    minWidth: 600,
    minHeight: 420,
    color: '#7c3aed',
  },
  {
    id: 'storage-manager',
    name: 'Gestor de Almacenamiento',
    icon: '💾',
    description: 'Gestión de discos, volúmenes y RAID',
    defaultWidth: 900,
    defaultHeight: 620,
    minWidth: 680,
    minHeight: 460,
    color: '#f97316',
  },
  {
    id: 'zfs-panel',
    name: 'Panel ZFS',
    icon: '🗄️',
    description: 'Gestión avanzada de pools y datasets ZFS',
    defaultWidth: 960,
    defaultHeight: 660,
    minWidth: 720,
    minHeight: 500,
    color: '#0284c7',
  },
  /* ─── Nuevas apps v1.1 ─── */
  {
    id: 'photo-station',
    name: 'Photo Station',
    icon: '🖼️',
    description: 'Galería de fotos con álbumes y visor EXIF',
    defaultWidth: 960,
    defaultHeight: 680,
    minWidth: 720,
    minHeight: 500,
    color: '#ec4899',
  },
  {
    id: 'note-station',
    name: 'Note Station',
    icon: '📝',
    description: 'Bloc de notas con Markdown, libretas y etiquetas',
    defaultWidth: 920,
    defaultHeight: 640,
    minWidth: 700,
    minHeight: 480,
    color: '#8b5cf6',
  },
  {
    id: 'music-player',
    name: 'Música',
    icon: '🎵',
    description: 'Reproductor de música con listas de reproducción',
    defaultWidth: 860,
    defaultHeight: 600,
    minWidth: 640,
    minHeight: 440,
    color: '#10b981',
  },
];

export const getApp = (id: string): AppDefinition | undefined =>
  APPS.find((a) => a.id === id);

