/**
 * Registro Central de Aplicaciones — LGM OS
 *
 * Arquitectura Modular:
 * - Core Apps: Cargadas en el bundle principal (Panel de Control)
 * - Store Apps: Cargadas con lazy loading desde el Package Center
 *
 * Cada app tiene un AppManifest completo con metadatos, permisos y
 * ruta de componente para importación dinámica.
 */

import type { AppManifest } from '../types/app';

export const MANIFESTS: AppManifest[] = [
  /* ════════════════════════════════════════════
     CORE APPS — Siempre disponibles en el sistema
     ════════════════════════════════════════════ */

  // ─── Sistema ───
  {
    id: 'control-panel',
    name: 'Panel de Control',
    icon: '⚙️',
    description: 'Configuración completa del sistema: red, almacenamiento, usuarios, seguridad',
    tagline: 'Centro de configuración del NAS',
    version: '1.0.0',
    category: 'system',
    isCore: true,
    defaultWidth: 980, defaultHeight: 660,
    minWidth: 760, minHeight: 520,
    color: '#6366f1',
    singleInstance: true,
    componentPath: './ControlPanel/ControlPanel',
    lazy: false,
    permissions: [{ resource: 'system:config', access: 'admin' }],
    size: '—', publisher: 'LGM OS Team',
  },
  {
    id: 'system-info',
    name: 'Monitor del Sistema',
    icon: '📊',
    description: 'CPU, RAM, disco, red y procesos en tiempo real',
    tagline: 'Telemetría y rendimiento',
    version: '1.0.0',
    category: 'system',
    isCore: true,
    defaultWidth: 820, defaultHeight: 580,
    minWidth: 600, minHeight: 420,
    color: '#ef4444',
    singleInstance: true,
    componentPath: './SystemInfo/SystemInfo',
    lazy: false,
    permissions: [{ resource: 'system:monitor', access: 'read' }],
    publisher: 'LGM OS Team',
  },
  {
    id: 'task-manager',
    name: 'Administrador de Tareas',
    icon: '📋',
    description: 'Gestión de procesos, servicios y tareas programadas',
    tagline: 'Procesos del sistema',
    version: '1.0.0',
    category: 'system',
    isCore: true,
    defaultWidth: 860, defaultHeight: 580,
    minWidth: 640, minHeight: 440,
    color: '#d946ef',
    singleInstance: true,
    componentPath: './TaskManager/TaskManager',
    lazy: false,
    permissions: [{ resource: 'system:processes', access: 'read' }],
    publisher: 'LGM OS Team',
  },
  {
    id: 'log-center',
    name: 'Centro de Registros',
    icon: '📜',
    description: 'Visor de logs del sistema',
    tagline: 'Auditoría y diagnóstico',
    version: '1.0.0',
    category: 'system',
    isCore: true,
    defaultWidth: 900, defaultHeight: 580,
    minWidth: 640, minHeight: 420,
    color: '#64748b',
    singleInstance: true,
    componentPath: './LogCenter/LogCenter',
    lazy: false,
    permissions: [{ resource: 'system:logs', access: 'read' }],
    publisher: 'LGM OS Team',
  },

  // ─── Almacenamiento ───
  {
    id: 'storage-manager',
    name: 'Gestor de Almacenamiento',
    icon: '💾',
    description: 'Gestión de discos, volúmenes RAID, carpetas compartidas y cuotas',
    tagline: 'Discos, volúmenes y cuotas',
    version: '1.0.0',
    category: 'storage',
    isCore: true,
    defaultWidth: 1040, defaultHeight: 660,
    minWidth: 780, minHeight: 500,
    color: '#f97316',
    singleInstance: true,
    componentPath: './StorageManager/StorageManager',
    lazy: false,
    permissions: [
      { resource: 'storage:disks', access: 'admin' },
      { resource: 'storage:volumes', access: 'admin' },
    ],
    publisher: 'LGM OS Team',
  },
  {
    id: 'zfs-panel',
    name: 'Panel ZFS',
    icon: '🗄️',
    description: 'Gestión avanzada de pools ZFS, datasets, snapshots y schedules',
    tagline: 'ZFS nativo',
    version: '1.0.0',
    category: 'storage',
    isCore: true,
    defaultWidth: 1100, defaultHeight: 700,
    minWidth: 840, minHeight: 540,
    color: '#0284c7',
    singleInstance: true,
    componentPath: './ZFSPanel/ZFSPanel',
    lazy: false,
    permissions: [{ resource: 'storage:zfs', access: 'admin' }],
    publisher: 'LGM OS Team',
  },

  // ─── Red ───
  {
    id: 'network-services',
    name: 'Servicios de Red',
    icon: '🌐',
    description: 'Configuración de SMB, NFS, FTP, SFTP, WebDAV y Rsync',
    tagline: 'SMB, NFS, FTP, SFTP…',
    version: '1.0.0',
    category: 'network',
    isCore: true,
    defaultWidth: 960, defaultHeight: 640,
    minWidth: 700, minHeight: 480,
    color: '#0891b2',
    singleInstance: true,
    componentPath: './NetworkServices/NetworkServices',
    lazy: false,
    permissions: [{ resource: 'network:services', access: 'admin' }],
    publisher: 'LGM OS Team',
  },
  {
    id: 'ssh-manager',
    name: 'SSH Manager',
    icon: '🔐',
    description: 'Gestión de conexiones SSH, claves autorizadas y sesiones activas',
    tagline: 'Terminal remota',
    version: '1.0.0',
    category: 'network',
    isCore: true,
    defaultWidth: 920, defaultHeight: 600,
    minWidth: 680, minHeight: 440,
    color: '#334155',
    singleInstance: true,
    componentPath: './SSHManager/SSHManager',
    lazy: false,
    permissions: [{ resource: 'network:ssh', access: 'admin' }],
    publisher: 'LGM OS Team',
  },
  {
    id: 'vpn-manager',
    name: 'VPN Manager',
    icon: '🔒',
    description: 'Configuración de servidores y clientes VPN (WireGuard, OpenVPN, IPsec)',
    tagline: 'WireGuard, OpenVPN…',
    version: '1.0.0',
    category: 'network',
    isCore: true,
    defaultWidth: 860, defaultHeight: 580,
    minWidth: 640, minHeight: 440,
    color: '#059669',
    singleInstance: true,
    componentPath: './VPNManager/VPNManager',
    lazy: false,
    permissions: [{ resource: 'network:vpn', access: 'admin' }],
    publisher: 'LGM OS Team',
  },

  // ─── Usuarios ───
  {
    id: 'user-manager',
    name: 'Usuarios y Grupos',
    icon: '👥',
    description: 'Administración de usuarios, grupos, permisos y cuotas de acceso',
    tagline: 'Gestión de cuentas',
    version: '1.0.0',
    category: 'users',
    isCore: true,
    defaultWidth: 1020, defaultHeight: 640,
    minWidth: 760, minHeight: 480,
    color: '#7c3aed',
    singleInstance: true,
    componentPath: './UserManager/UserManager',
    lazy: false,
    permissions: [{ resource: 'users:manage', access: 'admin' }],
    publisher: 'LGM OS Team',
  },

  /* ════════════════════════════════════════════
     STORE APPS — Requieren instalación desde Package Center
     ════════════════════════════════════════════ */

  // ─── Herramientas ───
  {
    id: 'terminal',
    name: 'Terminal',
    icon: '💻',
    description: 'Consola del sistema con múltiples pestañas y autocompletado',
    tagline: 'Consola bash integrada',
    version: '1.0.0',
    category: 'tools',
    isCore: false,
    defaultWidth: 720, defaultHeight: 460,
    minWidth: 400, minHeight: 300,
    color: '#1e3a5f',
    singleInstance: false,
    componentPath: './Terminal/Terminal',
    lazy: true,
    permissions: [{ resource: 'system:terminal', access: 'write' }],
    size: '1.2 MB',
    publisher: 'LGM OS Team',
    rating: 5, pulls: '10K+',
  },
  {
    id: 'text-editor',
    name: 'Editor de Texto',
    icon: '📝',
    description: 'Editor de archivos con múltiples pestañas y búsqueda',
    tagline: 'Edición de código y texto',
    version: '1.0.0',
    category: 'tools',
    isCore: false,
    defaultWidth: 760, defaultHeight: 560,
    minWidth: 420, minHeight: 320,
    color: '#3b82f6',
    singleInstance: false,
    componentPath: './TextEditor/TextEditor',
    lazy: true,
    permissions: [{ resource: 'storage:files', access: 'write' }],
    size: '0.8 MB',
    publisher: 'LGM OS Team',
    rating: 4, pulls: '8K+',
  },
  {
    id: 'calculator',
    name: 'Calculadora',
    icon: '🧮',
    description: 'Calculadora científica con operaciones básicas y avanzadas',
    tagline: 'Operaciones aritméticas',
    version: '1.0.0',
    category: 'tools',
    isCore: false,
    defaultWidth: 300, defaultHeight: 460,
    minWidth: 260, minHeight: 400,
    color: '#8b5cf6',
    singleInstance: true,
    componentPath: './Calculator/Calculator',
    lazy: true,
    permissions: [],
    size: '0.3 MB',
    publisher: 'LGM OS Team',
    rating: 4, pulls: '5K+',
  },

  // ─── Productividad ───
  {
    id: 'file-station',
    name: 'File Station',
    icon: '📁',
    description: 'Explorador de archivos avanzado con visor multimedia integrado',
    tagline: 'Gestor de archivos del NAS',
    version: '1.0.0',
    category: 'tools',
    isCore: false,
    defaultWidth: 920, defaultHeight: 620,
    minWidth: 640, minHeight: 420,
    color: '#f59e0b',
    singleInstance: true,
    componentPath: './FileStation/FileStation',
    lazy: true,
    permissions: [{ resource: 'storage:files', access: 'admin' }],
    size: '3.4 MB',
    publisher: 'LGM OS Team',
    rating: 5, pulls: '50K+',
  },
  {
    id: 'note-station',
    name: 'Note Station',
    icon: '📝',
    description: 'Bloc de notas con Markdown, libretas, etiquetas y favoritos',
    tagline: 'Tus notas en el NAS',
    version: '1.0.0',
    category: 'productivity',
    isCore: false,
    defaultWidth: 920, defaultHeight: 640,
    minWidth: 700, minHeight: 480,
    color: '#8b5cf6',
    singleInstance: true,
    componentPath: './NoteStation/NoteStation',
    lazy: true,
    permissions: [],
    size: '1.1 MB',
    publisher: 'LGM OS Team',
    rating: 4, pulls: '3K+',
  },

  // ─── Multimedia ───
  {
    id: 'photo-station',
    name: 'Photo Station',
    icon: '🖼️',
    description: 'Galería de fotos con álbumes, visor EXIF y búsqueda',
    tagline: 'Tus fotos organizadas',
    version: '1.0.0',
    category: 'multimedia',
    isCore: false,
    defaultWidth: 960, defaultHeight: 680,
    minWidth: 720, minHeight: 500,
    color: '#ec4899',
    singleInstance: true,
    componentPath: './PhotoStation/PhotoStation',
    lazy: true,
    permissions: [{ resource: 'storage:files', access: 'read' }],
    size: '1.8 MB',
    publisher: 'LGM OS Team',
    rating: 5, pulls: '2K+',
  },
  {
    id: 'music-player',
    name: 'Música',
    icon: '🎵',
    description: 'Reproductor de música con listas de reproducción por género',
    tagline: 'Tu biblioteca musical',
    version: '1.0.0',
    category: 'multimedia',
    isCore: false,
    defaultWidth: 860, defaultHeight: 600,
    minWidth: 640, minHeight: 440,
    color: '#10b981',
    singleInstance: true,
    componentPath: './MusicPlayer/MusicPlayer',
    lazy: true,
    permissions: [{ resource: 'storage:files', access: 'read' }],
    size: '1.5 MB',
    publisher: 'LGM OS Team',
    rating: 4, pulls: '4K+',
  },

  // ─── Sistema (Store) ───
  {
    id: 'package-center',
    name: 'Centro de Paquetes',
    icon: '📦',
    description: 'Tienda de aplicaciones con despliegue Docker integrado',
    tagline: 'Instala apps desde Docker Hub',
    version: '1.0.0',
    category: 'system',
    isCore: false,
    defaultWidth: 880, defaultHeight: 620,
    minWidth: 640, minHeight: 420,
    color: '#10b981',
    singleInstance: true,
    componentPath: './PackageCenter/PackageCenter',
    lazy: true,
    permissions: [{ resource: 'system:packages', access: 'admin' }],
    size: '4.2 MB',
    publisher: 'LGM OS Team',
    rating: 5, pulls: '20K+',
  },
];

export const getManifest = (id: string): AppManifest | undefined =>
  MANIFESTS.find(m => m.id === id);

export const getCoreApps = (): AppManifest[] =>
  MANIFESTS.filter(m => m.isCore);

export const getStoreApps = (): AppManifest[] =>
  MANIFESTS.filter(m => !m.isCore);

export const getAppsByCategory = (category: string): AppManifest[] =>
  MANIFESTS.filter(m => m.category === category);